language: ANDROID
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
notifications:
  slack: lp-iem:5VypeA9fibvKjUR6g85WcL2w

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/native"
  - "$HOME/.gradle/wrapper"

before_script:
- chmod +x ./build-apk.sh
script:
- "./build-apk.sh"